### ISSUE TITLE
_default_panel needs to check that pn.extension('tabulator') has been called when returning a tabulator widget

### ISSUE THREAD

**Issue by JL2435** [algol60/sier2#8]
If a block doesn't have a __panel__ function and it's in_ variable is a dataframe it will try and return a tabulator widget. if the user has not include pn.extension('tabulator') in their program nothing will be returned by  _default_panel.

For example, this will not show any widget in the FinishBlock
```

from sier2 import Block, Connection
from sier2.panel import PanelDag
import param
import time
import pandas as pd 
import panel as pn
   
class StartBlock(Block):
    """Starts the test dag"""

    out_data = param.DataFrame()

    def execute(self):
        time.sleep(3)
        self.out_data = pd.DataFrame({'A':[1,2,3,4], 'B':[5,6,7,8]})

class FinishBlock(Block):
    """Finishes the test dag"""
    in_data = param.DataFrame()

sb = StartBlock(block_pause_execution=True)
fb = FinishBlock()
dag = PanelDag(doc='test', title='test')
dag.connect(sb, fb, Connection('out_data', 'in_data'))
dag.show()
```

But if the user adds pn.extension('tabulator'). a tabulator will appear.

# Fix
A fix may be to check in pn.extension._loaded_extensions for 'tabulator' if the in_ variable is a dataframe
```
if 'tabulator' not in pn.extension._loaded_extensions:
    pn.extension._loaded_extensions.append('tabulator')
```

**Comment by jacobgolding** [comment]
Good catch, can you check if the solution in the branch linked above works?
As a broader conversation, should we generate an automatic panel view for blocks that are not pausing their execution?
I can see many use cases where we don't want blocks internal to a dag to display the same dataframe over and over that's being passed around. This could maybe be solved by a flag on whether to expand the card added to the panel dag for that block which can be set to False.

**Comment by JL2435** [comment]
Hey, 

No luck. Based on my example dag above the values in param_pane._widgets.values() are:
dict_values([DataFrame(name='Data')])


 I think instead of looking for tabulator it needs to look for dataframe. Maybe something like this

```
    for widget in param_pane._widgets.values():
        if 'DataFrame' in str(widget):
            pn.extension('tabulator')
            print(pn.extension._loaded_extensions)
```

This loads the pn.extension('tabulator') and you can see its loaded with that print statement but the dag still doesn't load the tabulator. Not sure what's going on with that.

**Comment by jacobgolding** [comment]
Roger. I'd imagine the issue is that we've already made the widgets before we check... I've just pushed a new version (before I saw your commend) which adds a user warning, but I'll tinker with the above more and let you know.

**Comment by jacobgolding** [comment]
Newest push should work. It checks the parameter types looking for DataFrame before we build the widgets. I was able to get your toy example working, want to confirm for me before I merge?

**Comment by JL2435** [comment]
Hey i might be blind, but can't see any new commits.

**Comment by JL2435** [comment]
Yeah looks all good
